### ISSUE TITLE
Errno: 109, Unauthorized on firefox 59 autopush

### ISSUE THREAD

**Issue by lellefood** [gauntface/web-push-book#108]
I'm trying to use the [demo server](https://github.com/gauntface/web-push-book/tree/master/src/demos/node-server).

It works correctly and sends the push message to Chorme 65 on Ubuntu 16.04 but on the same device using Firefox 59 i get this:

```
Subscription is no longer valid:  { WebPushError: Received unexpected response code
    at IncomingMessage.<anonymous> (/home/food/dev/web_push_server/node_modules/web-push/src/web-push-lib.js:298:20)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'WebPushError',
  message: 'Received unexpected response code',
  statusCode: 401,
  headers: 
   { 'access-control-allow-headers': 'content-encoding,encryption,crypto-key,ttl,encryption-key,content-type,authorization',
     'access-control-allow-methods': 'POST',
     'access-control-allow-origin': '*',
     'access-control-expose-headers': 'location,www-authenticate',
     'content-type': 'application/json',
     date: 'Mon, 19 Mar 2018 13:57:55 GMT',
     server: 'nginx',
     'strict-transport-security': 'max-age=31536000;includeSubDomains',
     'content-length': '199',
     connection: 'Close' },
  body: '{"code": 401, "errno": 109, "error": "Unauthorized", "more_info": "http://autopush.readthedocs.io/en/latest/http.html#error-codes", "message": "Request did not validate missing authorization header"}',
  endpoint: 'https://updates.push.services.mozilla.com/wpush/v2/AAAA<other part of my endpoint>' }
```

What am I doing wrong?

**Comment by gauntface** [comment]
From the [linked docs](http://autopush.readthedocs.io/en/latest/http.html#error-codes):

> 401 - Bad Authorization - Authorization header is invalid or missing. See the VAPID specification.
